### ISSUE TITLE
Does it support character classes?

### ISSUE THREAD

**Issue by alamothe** [fulmicoton/multiregexp#12]
Hello, 
I read https://fulmicoton.com/posts/multiregexp/ and I'm amazed by the work.

Does it support character classes? In particular, I'm, interested in Unicode word character class

**Comment by fulmicoton** [comment]
No, The compilation of individual regular expression into an Automaton is handled by [dk.brics](http://www.brics.dk/automaton/doc/index.html), and its simple dialect does not handle Unicode word character class.
