### ISSUE TITLE
What if I want to match (^\d{2,4}年)?\d{1,2}月\d{1,2}日$

### ISSUE THREAD

**Issue by wihoho** [fulmicoton/multiregexp#5]
Hi fulmicoton, 

Thanks for this great package.

However, I need to match unicode patterns. What can I do to resolve such cases? Thanks.

**Comment by fulmicoton** [comment]
Hi, the library does not take care of the compilation of regular expression. dk.brics does that.
Unfortunately dk.brics only handles a restricted version of what you might be used to.

In your case you need to write your regex like that :

    ([0-9]{2,4}年)?[0-9]{1,2}月[0-9]{1,2}日

**Comment by wihoho** [comment]
Yeah, I understand.

Are there any other alternatives? or do you plan to change in the near future?

**Comment by fulmicoton** [comment]
I would have to rewrite the whole compilation of regular expression.
This is absolutely something that can be done but it is quite a big piece of work... Considering the low number of user of this library, I don't intend to fix this in the near future.

**Comment by wihoho** [comment]
For your information, I found a project which is able to parse regular expression and build their own proposed DFA.

https://github.com/nes1983/tree-regex
